version: '3'
services:
  node1:
    container_name: node-1
    build: .
    cap_add:
      - ALL
    command: bash -c "./start-apis.sh"
    volumes:
      - ./miner:/root/miner
      - ./dashboard:/root/dashboard
      - ./runtime/node-1:/root/start
      - ./Apiscerana/apiscerana-microservice-iam/target:/root/apiscerana
    networks:
      vpcbr:
        ipv4_address: 10.7.0.11
    ports:
      - "35001:8080"
      - "5000:5000"
  node2:
    container_name: node-2
    build: .
    cap_add:
      - ALL
    command: bash -c "./start-apis.sh"
    volumes:
      - ./miner:/root/miner
      - ./runtime/node-2:/root/start
      - ./Apiscerana/apiscerana-microservice-iam/target:/root/apiscerana
    networks:
      vpcbr:
        ipv4_address: 10.7.0.12
    ports:
      - "35002:8080"
  node3:
    container_name: node-3
    build: .
    cap_add:
      - ALL
    command: bash -c "./start-apis.sh"
    volumes:
      - ./miner:/root/miner
      - ./runtime/node-3:/root/start
      - ./Apiscerana/apiscerana-microservice-iam/target:/root/apiscerana
    networks:
      vpcbr:
        ipv4_address: 10.7.0.13
    ports:
      - "35003:8080"
  node4:
    container_name: node-4
    build: .
    cap_add:
      - ALL
    command: bash -c "./start-apis.sh"
    volumes:
      - ./miner:/root/miner
      - ./runtime/node-4:/root/start
      - ./Apiscerana/apiscerana-microservice-iam/target:/root/apiscerana
    networks:
      vpcbr:
        ipv4_address: 10.7.0.14
    ports:
      - "35004:8080"
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.7.0.0/16
